services:
  serve:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["python", "/app/src/main/python/app.py"]
    environment:
      - TRACK_TERM=${TRACK_TERM}
      - TRACK_ENTAILMENTS=${TRACK_ENTAILMENTS}
    volumes:
      - type: bind
        source: logs
        target: /logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
